### ISSUE TITLE
genewise dispersion estimate orders of magnitude too high

### ISSUE THREAD

**Issue by frederikziebell** [mikelove/DESeq2#10]
I find that for many genes in my data set, the gene-wise dispersion estimates are 3 orders of magnitude higher than expected. I set up a minimal example at https://github.com/frederikziebell/deseq2-bug. There it seems that the preliminary dispersion estimate is ok, but since the estimation did not converge, re-fitting with `fitDispGrid` intoduces the high dispersion estimate.

**Comment by mikelove** [comment]
hi Frederik,

Thanks for the reproducible example. A few notes, why this isn't a bug:

Because you have a design of `~condition+run`, this means that `(Var - Mu) / Mu^2` is not an appropriate estimator for the dispersion, where `Var` is the variance over all samples and `Mu` is the mean over all samples. This would be the method of moments estimator if the design were `~1`.

Secondly, the method of moments estimator has a negative bias, which is discussed in the edgeR paper that proposes to instead use the Cox-Reid adjusted likelihood, which is what we use.

Thirdly, because the default routine does not converge, it shouldn't be taken as ground truth. It's possibly a good estimate, or it could be that the fitting routine is stuck or taking a long time to move to a better estimate.
