### ISSUE TITLE
Rownames of HTSeq counts not recognized with DESeqDataSetFromHTSeqCount

### ISSUE THREAD

**Issue by RoganGrant** [mikelove/DESeq2#15]
edit: using version 1.24.0

I am working with data from a collaboration that includes HTSeq output in the following format, without an explicit rownames column:

```
	sample_x
ENSMUSG00000000001	288
ENSMUSG00000000003	0
ENSMUSG00000000028	4
ENSMUSG00000000031	0
ENSMUSG00000000037	0
ENSMUSG00000000049	4
ENSMUSG00000000056	40
ENSMUSG00000000058	944
ENSMUSG00000000078	480
ENSMUSG00000000085	80
```
When I run `DESeqDataSetFromHTSeqCount()`, I get the following error: 

> Error in DESeqDataSet(se, design = design, ignoreRank) : 
  all samples have 0 counts for all genes. check the counting script.

The sample table, design formula, and directory are all as expected. It seems that the issue lies in this line of code in `DESeqDataSetFromHTSeqCount()`:

```
rownames(tbl) <- l[[1]]$V1
```

In my case there is no V1, because the rownames are already set for each file. After the following line, `specialRows` is set to an empty vector, since none of the rows are named:

```
specialRows <- (substr(rownames(tbl), 1, 1) == "_") | rownames(tbl) %in% 
    oldSpecialNames
```
and, as such, `!specialRows` also evaluates to an empty vector. The subset then removes all rows from `tbl`:

```
tbl <- tbl[!specialRows, , drop = FALSE]
```

The following checkpoint also fails because V1 is always NULL:

```
if (!all(sapply(l, function(a) all(a$V1 == l[[1]]$V1)))) 
    stop("Gene IDs (first column) differ between files.")
```

Would it be possible to check if V1 exists, and, if not, use the rownames of each item in `l`? It may be that this is a nonstandard output format, in which case I can obviously just edit the HTSeq files in batch.

Thanks in advance!

**Comment by mikelove** [comment]
hi Rogan,

I'd prefer to not modify this function: it has stayed the same since DESeq (original package), without modification, so I think it must work fine on standard htseq output given that probably loads of people have fed htseq files into DESeq2, and I've never heard of an issue.

My guess is that the collaborator has modified the files a bit. This is usually not a great idea to modify the output files of any standard software because it breaks downstream workflows, e.g. it will break someone trying to feed the files into Galaxy, etc.

The easier approach would be to combine what you've got with some R code and then provide it to `DESeqDataSetFromMatrix`.

**Comment by RoganGrant** [comment]
Fair points - I will fix the files. Thanks for the quick response!
