### ISSUE TITLE
Different result

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [mikelove/DESeq2#33]
Hi,
    One read with same count number in two group but the contrast with different log. 
    The normal result is like that (A2_A4 A5 belong to BW group, N8 N7 belong to N group), the log value of line 1 is -7.98641"
![image](https://user-images.githubusercontent.com/46480129/103756544-7b37f980-504a-11eb-9668-aa47573fdac3.png)
![image](https://user-images.githubusercontent.com/46480129/103756573-868b2500-504a-11eb-90cf-3d4a43ddeb62.png)
"
    But the other file (only some read and count are same) with differnet result like that, the log value of line 1 (same read and counts) is 3.86641 "
![image](https://user-images.githubusercontent.com/46480129/103756809-d669ec00-504a-11eb-964b-bd0cc1319355.png)
![image](https://user-images.githubusercontent.com/46480129/103756843-e1248100-504a-11eb-92a1-d11cda2338bb.png)
" 
    Could you please tell me is there anything wrong?
    Thanks in advance.
Best wishes.
Liu

**Comment by mikelove** [comment]
I can't help debug this because there isn't enough information: the two images are the same, and you don't say how the two analyses differ. The same data and same code will give the same result.

If you can find a way to post with the information about how the analyses differ, could you post here instead:

https://support.bioconductor.org
