### ISSUE TITLE
row-subsetting gives error if rowData contains GRanges column names

### ISSUE THREAD

**Issue by frederikziebell** [mikelove/DESeq2#42]
Hi Mike, 

here's an example of the problem

```
se <- SummarizedExperiment(assays = matrix(1:4, ncol = 2), rowData = DataFrame(start = c(1,1)))
dds <- DESeqDataSet(se, design = ~1)
validObject(dds)
# TRUE
dds[1,]
```

which returns `Error in validObject(.Object) : invalid class "CompressedGRangesList" object: 'mcols(x)' cannot have columns named "seqnames", "ranges", "strand", "start", "end", "width", or "element"`.

My use-case is that I don't want to bother with genomic ranges and just store genomic information (chromosome, start and end position, biotype) in the rowData slot.

I think it would be best if arbitriary rowData columns are allowed if the DESeqData set is created from a non-RangedSummarizedExperiment or at least throw an error already during object creation, that some 'mcols'-names are not allowed.

**Comment by mikelove** [comment]
This is upstream of DESeq2, in SummarizedExperiment you can't name metadata columns in rowData as in the list above.  Those are reserved variable names according to the upstream package. Because the particular reserved names are upstream of DESeq2, I'd prefer not to enumerate those in my package as it may get out of date.

Out of curiosity, why not just GRanges? Is there a particular concern? I find it incredibly useful that GRanges has a `genome()` slot in particular, as coordinates are of limited value without knowing the genome being referenced.

**Comment by frederikziebell** [comment]
I see the problem now:
```
se <- SummarizedExperiment(assays = matrix(1:4, ncol = 2), rowData = DataFrame(start = c(1,1)))
rse <- as(se,"RangedSummarizedExperiment")
rse[1,]
```
When casting to RangedSummarizedExperiment, there should be an error that certain `rowData` columns are not allowed, not just during subsetting. I'll file an issue with SummarizedExperiment. 

I never actually used GRanges because I felt it adds unneccesary of overhead for the small things I wanted to achieve, e.g. plot gene expression along a chromosme, for which a few additional rowData slots would be sufficient. I will look into it, GRanges seems to be the proper way to add those info.

**Comment by mikelove** [comment]
hi Frederik, 

Thanks for the followup and the reproducible examples. I'll just note that GRanges seems like overhead, but you'll notice it doesn't have any additional memory usage. It employs sparse representations (like RLE) for things like chromosome, and then has convenient slots in my opinion, such as `genome()`.
