### ISSUE TITLE
  Failed to find a rowRanges() issue

### ISSUE THREAD

**Issue by SNgalaxy** [mikelove/DESeq2#46]
Hello,

I have been working with DESeq2 package perfectly until I installed another package. Now when making a dds object, I get this error.

Error in MatrixGenerics:::.load_next_suggested_package_to_search(x) : 
  Failed to find a rowRanges() method for RangedSummarizedExperiment objects.

My R package version is: R 4.0.2 (2020-06-22)
Bioconductor version 3.12 (BiocManager 1.30.16)

I have updated my Bioconductor and all the dependent packages. However, it still doesn't work even with the example dataset.
I appreciate it if you could lead me through solving this issue
Thanks,
Shadi

**Comment by const-ae** [comment]
Hi Shadi,

I am one of the maintainers of [MatrixGenerics](https://github.com/Bioconductor/MatrixGenerics) and my guess is that the issue that you encountered is rather related to that package instead of _DESeq2_.

Except if Mike says that it is something _DESeq2_ related, I would suggest that you open a new issue in the [MatrixGenerics](https://github.com/Bioconductor/MatrixGenerics) repo. And if you do, could you please provide a small [reproducible example](https://reprex.tidyverse.org/) because the exact order in which load the packages is probably important for debugging the issue.

Best,
Constantin

**Comment by mikelove** [comment]
Yeah, DESeq2 (core) doesn't depend on MatrixGenerics. Agree with @const-ae

**Comment by SNgalaxy** [comment]
I will, thanks

**Comment by mikelove** [comment]
I'm going to close unless there is additional notes here.
