### ISSUE TITLE
DESEq2 error

### ISSUE THREAD

**Issue by imrjesh** [mikelove/DESeq2#80]
Hi Mike
I have a dataframe on which i want to run the DESeq2 usin following code
tpm_counts = read.table("/count.csv", header = T, sep = ",", check.names=F, row.names = 1)
df_anno = read.table("/metadata.tsv", header = T, sep = "\t")
dds <- DESeqDataSetFromMatrix(countData = round(filtered_data[, df_anno$generation]),
                              colData = df_anno, design =  design.tmp)

keep <- rowSums(counts(dds)) >= 10
dds.filtered <- dds[keep,]

dds.filtered <- DESeq(dds.filtered)
But stuck with an error Error in estimateDispersionsFit(object, fitType = fitType, quiet = quiet) : 
  all gene-wise dispersion estimates are within 2 orders of magnitude

<img width="768" alt="Screenshot 2023-08-09 at 2 34 52 PM" src="https://github.com/mikelove/DESeq2/assets/111061685/cc04110b-6f99-4ce6-b4c0-fe1595345dd9">

**Comment by luciorq** [comment]
This looks more like a usage question and not a package code-related problem.

Post your question to the Bioconductor Support page: <https://support.bioconductor.org/>. More people can help you there.

It would also be helpful to have a [reproducible example](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one) since it looks like something particular to your data.
